"""This file is generated by test_case_generator"""
from typing import NamedTuple, Callable

from test_case_generator import generate_test_case


def test_generate_test_case():
    class Args(NamedTuple):
        func: Callable

    class Test(NamedTuple):
        name: str
        args: Args
        want: str

    cases: tuple[Test] = (
        Test(
            "Test on itself",
            Args(generate_test_case),
            """\n
def test_generate_test_case():
    class Args(NamedTuple):
        func: Callable

    class Test(NamedTuple):
        name: str
        args: Args
        want: str

    cases: tuple[Test] = (
        # TODO: add cases here
    )
    print(f"running test cases for generate_test_case function:")
    for case in cases:
        if (v := generate_test_case(*case.args)) != case.want:
            print(f"{case.name} generate_test_case got {v}, wanted {case.want}")
         """,
        ),
    )
    print(f"running test cases for generate_test_case function:\n")
    for case in cases:
        if (v := generate_test_case(*case.args)) != case.want:
            print(f"{case.name} generate_test_case got {v} wanted {case.want}\n")
    print('Test complited')

if __name__ == "__main__":
    test_generate_test_case()
